name: The Daily Muzz RSS Newsletter

on:
  schedule:
    # Runs every day at 7am UTC
    - cron: '0 7 * * *'
  # manual trigger
  workflow_dispatch:

jobs:
  rss-fetch-send:
    name: Fetch RSS articles and Send Email
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

    #   - name: Navigate to server directory
    #     run: cd server
      
      - name: Display contents
        run: ls -la 
      
      - name: Install dependencies
        run: npm install

      - name: Run Daily RSS fetch & send
        env:
          DB_CLIENT: ${{ secrets.DB_CLIENT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: node scheduler.js
